steps:
- name: 'node:14'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    npm install
    npm run build
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['rsync', '-r', 'build/', 'gs://react_demo_bucket798']

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud compute ssh instance-ngnix-app --zone asia-south2-a --command "sudo rm -rf /var/www/html/*"
    gcloud compute scp --recurse gs://react_demo_bucket798/* instance-ngnix-app:/var/www/html --zone asia-south2-a
