steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['rsync', '-r', '/workspace/', 'gs://react_demo_bucket798']

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud compute ssh instance-ngnix-app --zone asia-south2-a --command "sudo gsutil -m rsync -r gs://react_demo_bucket798 /var/www/html"

logsBucket: 'gs://react-cicd-log798'
options:
  logging: GCS_ONLY
